version: "3"
services:
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: dockerfile.prod
    env_file:
      - .env
    command: npm start
    volumes:
      - ./src/logs:/app/src/logs

  nginx:
      dockerfile: dockerfile
      context: ./nginx
      ports:
        - "80:80"
      depends_on:
        - app

  postgres-prod:
    image: postgres:11
    ports:
      - "5433:5432"  # Mapping container port 5432 to host port 5433
    environment:
      POSTGRES_DB: ${PGDATABASENAMEPROD}
      POSTGRES_USER: ${PGUSERPROD}
      POSTGRES_PASSWORD: ${PGPASSWORDPROD}
      POSTGRES_PORT: '5432'
    volumes:
      - postgres-prod-data:/var/lib/postgresql/data

volumes:
  postgres-prod-data:
