version: "3"
services:
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: dockerfile.prod
    container_name: app
    env_file:
      - .env
    command: npm start
    volumes:
      - ./src/logs:/app/src/logs

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app

  postgres-prod:
    image: postgres:11
    container_name: postgres-prod
    ports:
      - "5433:5432"  # Mapping container port 5432 to host port 5433
    environment:
      POSTGRES_DB: ${PGDATABASENAMEPROD}
      POSTGRES_USER: ${PGUSERPROD}
      POSTGRES_PASSWORD: ${PGPASSWORDPROD}
      POSTGRES_PORT: '5432'
#     volumes:
#       - postgres-prod-data:/var/lib/postgresql/data

# volumes:
#   postgres-prod-data: